### ISSUE TITLE
Making the tuple struct's value public

### ISSUE THREAD

**Issue by Zabaniya001** [MaulingMonkey/minidl#9]
Hello. Another day another issue! I hope I'm not bothering you by making yet another issue.

Could we make `Library`'s value ( value being the base address of the module ) public? There are instances where other libraries might need to access a function through an offset, in addition through a symbol ( detour libraries for example ). 

I understand that adding this functionality ( as in another method like `sym` but with an offset instead ) might be out of scope for this project, or "dangerous" per-se, and I'm not suggesting that. However, it'd be beneficial to at least have the possibility to retrieve the base address of the module. Without this, libraries are forced to manually reimplement `Library::load(...)`, leading to additional dependencies and somewhat defeating the purpose of this library. 

We could either make the field public or create a function that returns it. The latter would provide more control over the implementation, since I feel like straight up returning a `*mut c_void` might be undesirable, where we could return either a `*const c_void` or a even a `usize`, which would simplify things.

**Comment by Zabaniya001** [comment]
> Making `0` `pub` would make `Library::has_sym` unsound, as it's a safe fn that assumes `0` is a valid library handle via calling sym_opt. Accessors would be appropriate however - the only question is what type they should have. I've been dragging my feet on this as the following types can all be distinct:
> 
> * [`core::ffi::c_void`](https://doc.rust-lang.org/core/ffi/enum.c_void.html)
> * [`winapi::ctypes::c_void`](https://docs.rs/winapi/latest/winapi/ctypes/enum.c_void.html) ([without `feature = "std"`](https://github.com/retep998/winapi-rs/blob/5b1829956ef645f3c2f8236ba18bb198ca4c2468/src/lib.rs#L35-L38))
> * [`libc::c_void`](https://docs.rs/libc/latest/libc/enum.c_void.html) ([before rustc 1.30](https://github.com/rust-lang/libc/blob/497ac428bc010b5db9682ecf94cd567b31d53e5c/build.rs#L112-L117))
> 
> At this point I should probably just start using `core::ffi::c_void` and blame the user for any problems.

Ultimately they're all supposed to match the same thing, as in a C's void, so we can just go with `core::ffi::c_void` so we don't have any additional dependencies

**Comment by MaulingMonkey** [comment]
`minidl = "0.1.6"` / https://github.com/MaulingMonkey/minidl/commit/6599152672997f514b67ac742837fbb4f1c320d8 introduces <code><b>unsafe</b> fn [Library](https://docs.rs/minidl/0.1.6/minidl/struct.Library.html)::{[from_ptr](https://docs.rs/minidl/0.1.6/minidl/struct.Library.html#method.from_ptr), [as_ptr](https://docs.rs/minidl/0.1.6/minidl/struct.Library.html#method.as_ptr), ...}</code>

**Comment by tsuza** [comment]
That's great. Thank you!
